// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/payment/payment.proto

package payment

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payment status enum
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PROCESSING  PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_COMPLETED   PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_CANCELED    PaymentStatus = 5
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_PROCESSING",
		3: "PAYMENT_STATUS_COMPLETED",
		4: "PAYMENT_STATUS_FAILED",
		5: "PAYMENT_STATUS_CANCELED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_PROCESSING":  2,
		"PAYMENT_STATUS_COMPLETED":   3,
		"PAYMENT_STATUS_FAILED":      4,
		"PAYMENT_STATUS_CANCELED":    5,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_payment_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_api_proto_payment_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{0}
}

type Payment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount           float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency         string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status           PaymentStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	CreatedBy        uint32                 `protobuf:"varint,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt        *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PaymentNumber    string                 `protobuf:"bytes,9,opt,name=payment_number,json=paymentNumber,proto3" json:"payment_number,omitempty"`
	BillId           string                 `protobuf:"bytes,10,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	Method           string                 `protobuf:"bytes,11,opt,name=method,proto3" json:"method,omitempty"`
	GatewayReference string                 `protobuf:"bytes,12,opt,name=gateway_reference,json=gatewayReference,proto3" json:"gateway_reference,omitempty"`
	PaidAt           *timestamp.Timestamp   `protobuf:"bytes,13,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Payment) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Payment) GetPaymentNumber() string {
	if x != nil {
		return x.PaymentNumber
	}
	return ""
}

func (x *Payment) GetBillId() string {
	if x != nil {
		return x.BillId
	}
	return ""
}

func (x *Payment) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Payment) GetGatewayReference() string {
	if x != nil {
		return x.GatewayReference
	}
	return ""
}

func (x *Payment) GetPaidAt() *timestamp.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	BillNumber    string                 `protobuf:"bytes,2,opt,name=bill_number,json=billNumber,proto3" json:"bill_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreatePaymentRequest) GetBillNumber() string {
	if x != nil {
		return x.BillNumber
	}
	return ""
}

type UpdatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentRequest) Reset() {
	*x = UpdatePaymentRequest{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRequest) ProtoMessage() {}

func (x *UpdatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePaymentRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePaymentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePaymentRequest) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	BillId        string                 `protobuf:"bytes,5,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	PaymentNumber string                 `protobuf:"bytes,6,opt,name=payment_number,json=paymentNumber,proto3" json:"payment_number,omitempty"`
	Method        string                 `protobuf:"bytes,7,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsRequest) Reset() {
	*x = ListPaymentsRequest{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsRequest) ProtoMessage() {}

func (x *ListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *ListPaymentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPaymentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPaymentsRequest) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *ListPaymentsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ListPaymentsRequest) GetBillId() string {
	if x != nil {
		return x.BillId
	}
	return ""
}

func (x *ListPaymentsRequest) GetPaymentNumber() string {
	if x != nil {
		return x.PaymentNumber
	}
	return ""
}

func (x *ListPaymentsRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type ListPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsResponse) Reset() {
	*x = ListPaymentsResponse{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsResponse) ProtoMessage() {}

func (x *ListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ListPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *ListPaymentsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListPaymentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPaymentsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Payment               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentResponse) GetData() *Payment {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_payment_payment_proto protoreflect.FileDescriptor

const file_api_proto_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/payment/payment.proto\x12\apayment\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x03\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\rR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12%\n" +
	"\x0epayment_number\x18\t \x01(\tR\rpaymentNumber\x12\x17\n" +
	"\abill_id\x18\n" +
	" \x01(\tR\x06billId\x12\x16\n" +
	"\x06method\x18\v \x01(\tR\x06method\x12+\n" +
	"\x11gateway_reference\x18\f \x01(\tR\x10gatewayReference\x123\n" +
	"\apaid_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\"O\n" +
	"\x14CreatePaymentRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1f\n" +
	"\vbill_number\x18\x02 \x01(\tR\n" +
	"billNumber\"x\n" +
	"\x14UpdatePaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\"#\n" +
	"\x11GetPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xea\x01\n" +
	"\x13ListPaymentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x17\n" +
	"\abill_id\x18\x05 \x01(\tR\x06billId\x12%\n" +
	"\x0epayment_number\x18\x06 \x01(\tR\rpaymentNumber\x12\x16\n" +
	"\x06method\x18\a \x01(\tR\x06method\"\x96\x01\n" +
	"\x14ListPaymentsResponse\x12,\n" +
	"\bpayments\x18\x01 \x03(\v2\x10.payment.PaymentR\bpayments\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"Q\n" +
	"\x0fPaymentResponse\x12$\n" +
	"\x04data\x18\x01 \x01(\v2\x10.payment.PaymentR\x04data\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xc0\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_STATUS_PROCESSING\x10\x02\x12\x1c\n" +
	"\x18PAYMENT_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x04\x12\x1b\n" +
	"\x17PAYMENT_STATUS_CANCELED\x10\x052\xb5\x02\n" +
	"\x0ePaymentService\x12H\n" +
	"\rCreatePayment\x12\x1d.payment.CreatePaymentRequest\x1a\x18.payment.PaymentResponse\x12B\n" +
	"\n" +
	"GetPayment\x12\x1a.payment.GetPaymentRequest\x1a\x18.payment.PaymentResponse\x12K\n" +
	"\fListPayments\x12\x1c.payment.ListPaymentsRequest\x1a\x1d.payment.ListPaymentsResponse\x12H\n" +
	"\rUpdatePayment\x12\x1d.payment.UpdatePaymentRequest\x1a\x18.payment.PaymentResponseB3Z1github.com/novriyantoAli/moodly/api/proto/paymentb\x06proto3"

var (
	file_api_proto_payment_payment_proto_rawDescOnce sync.Once
	file_api_proto_payment_payment_proto_rawDescData []byte
)

func file_api_proto_payment_payment_proto_rawDescGZIP() []byte {
	file_api_proto_payment_payment_proto_rawDescOnce.Do(func() {
		file_api_proto_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_payment_payment_proto_rawDesc), len(file_api_proto_payment_payment_proto_rawDesc)))
	})
	return file_api_proto_payment_payment_proto_rawDescData
}

var file_api_proto_payment_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_payment_payment_proto_goTypes = []any{
	(PaymentStatus)(0),           // 0: payment.PaymentStatus
	(*Payment)(nil),              // 1: payment.Payment
	(*CreatePaymentRequest)(nil), // 2: payment.CreatePaymentRequest
	(*UpdatePaymentRequest)(nil), // 3: payment.UpdatePaymentRequest
	(*GetPaymentRequest)(nil),    // 4: payment.GetPaymentRequest
	(*ListPaymentsRequest)(nil),  // 5: payment.ListPaymentsRequest
	(*ListPaymentsResponse)(nil), // 6: payment.ListPaymentsResponse
	(*PaymentResponse)(nil),      // 7: payment.PaymentResponse
	(*timestamp.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_api_proto_payment_payment_proto_depIdxs = []int32{
	0,  // 0: payment.Payment.status:type_name -> payment.PaymentStatus
	8,  // 1: payment.Payment.created_at:type_name -> google.protobuf.Timestamp
	8,  // 2: payment.Payment.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 3: payment.Payment.paid_at:type_name -> google.protobuf.Timestamp
	0,  // 4: payment.UpdatePaymentRequest.status:type_name -> payment.PaymentStatus
	0,  // 5: payment.ListPaymentsRequest.status:type_name -> payment.PaymentStatus
	1,  // 6: payment.ListPaymentsResponse.payments:type_name -> payment.Payment
	1,  // 7: payment.PaymentResponse.data:type_name -> payment.Payment
	2,  // 8: payment.PaymentService.CreatePayment:input_type -> payment.CreatePaymentRequest
	4,  // 9: payment.PaymentService.GetPayment:input_type -> payment.GetPaymentRequest
	5,  // 10: payment.PaymentService.ListPayments:input_type -> payment.ListPaymentsRequest
	3,  // 11: payment.PaymentService.UpdatePayment:input_type -> payment.UpdatePaymentRequest
	7,  // 12: payment.PaymentService.CreatePayment:output_type -> payment.PaymentResponse
	7,  // 13: payment.PaymentService.GetPayment:output_type -> payment.PaymentResponse
	6,  // 14: payment.PaymentService.ListPayments:output_type -> payment.ListPaymentsResponse
	7,  // 15: payment.PaymentService.UpdatePayment:output_type -> payment.PaymentResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_payment_payment_proto_init() }
func file_api_proto_payment_payment_proto_init() {
	if File_api_proto_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_payment_payment_proto_rawDesc), len(file_api_proto_payment_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_payment_payment_proto_goTypes,
		DependencyIndexes: file_api_proto_payment_payment_proto_depIdxs,
		EnumInfos:         file_api_proto_payment_payment_proto_enumTypes,
		MessageInfos:      file_api_proto_payment_payment_proto_msgTypes,
	}.Build()
	File_api_proto_payment_payment_proto = out.File
	file_api_proto_payment_payment_proto_goTypes = nil
	file_api_proto_payment_payment_proto_depIdxs = nil
}
