package api

import (
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"go.uber.org/zap"

	authHandler "github.com/novriyantoAli/moodly/internal/application/auth/handler"
	billHandler "github.com/novriyantoAli/moodly/internal/application/bill/handler"
	oauthHandler "github.com/novriyantoAli/moodly/internal/application/oauth/handler"
	paymentHandler "github.com/novriyantoAli/moodly/internal/application/payment/handler"
	scanHandler "github.com/novriyantoAli/moodly/internal/application/scan/handler"
	securityHandler "github.com/novriyantoAli/moodly/internal/application/security/handler"
	subscribeHandler "github.com/novriyantoAli/moodly/internal/application/subscribe/handler"
	userHandler "github.com/novriyantoAli/moodly/internal/application/user/handler"
	"github.com/novriyantoAli/moodly/internal/middleware"
	"github.com/novriyantoAli/moodly/internal/pkg/jwt"

	_ "github.com/novriyantoAli/moodly/docs" // This will be generated by swag
)

type Server struct {
	oauthHandler       *oauthHandler.OAuthHandler
	userHandler        *userHandler.UserHandler
	paymentHandler     *paymentHandler.PaymentHandler
	subscribeHandler   *subscribeHandler.SubscribeHandler
	billHandler        *billHandler.BillHandler
	scanHandler        *scanHandler.ScanHandler
	userPINHandler     *securityHandler.UserPINHandler
	loginHandler       *authHandler.LoginHandler
	googleLoginHandler *authHandler.GoogleLoginHandler
	logoutHandler      *authHandler.LogoutHandler
	jwtManager         *jwt.JWTManager
	logger             *zap.Logger
}

func NewServer(
	oauthHandler *oauthHandler.OAuthHandler,
	userHandler *userHandler.UserHandler,
	userPINHandler *securityHandler.UserPINHandler,
	paymentHandler *paymentHandler.PaymentHandler,
	subscribeHandler *subscribeHandler.SubscribeHandler,
	billHandler *billHandler.BillHandler,
	scanHandler *scanHandler.ScanHandler,
	loginHandler *authHandler.LoginHandler,
	googleLoginHandler *authHandler.GoogleLoginHandler,
	logoutHandler *authHandler.LogoutHandler,
	jwtManager *jwt.JWTManager,
	logger *zap.Logger,
) *Server {
	return &Server{
		oauthHandler:       oauthHandler,
		userHandler:        userHandler,
		paymentHandler:     paymentHandler,
		subscribeHandler:   subscribeHandler,
		billHandler:        billHandler,
		scanHandler:        scanHandler,
		userPINHandler:     userPINHandler,
		loginHandler:       loginHandler,
		googleLoginHandler: googleLoginHandler,
		logoutHandler:      logoutHandler,
		jwtManager:         jwtManager,
		logger:             logger,
	}
}

func (s *Server) SetupRoutes(router *gin.Engine) {
	// Apply global middleware
	router.Use(middleware.Logger(s.logger))
	router.Use(middleware.Recovery(s.logger))
	router.Use(middleware.CORS())
	// router.Use(middleware.JWTMiddleware(s.jwtManager))

	// Swagger documentation routes
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	router.GET("/docs", func(c *gin.Context) {
		c.Redirect(302, "/swagger/index.html")
	})

	auth := router.Group("/auth")
	{
		s.loginHandler.RegisterRoutes(auth)
		s.googleLoginHandler.RegisterRoutes(auth)
	}

	// Register API routes
	api := router.Group("/api/v1")
	api.Use(middleware.JWTMiddleware(s.jwtManager))
	{
		s.registerHealthRoutes(api)
		// s.oauthHandler.RegisterRoutes(api)
		s.userHandler.RegisterRoutes(api)
		s.paymentHandler.RegisterRoutes(api)
		s.subscribeHandler.RegisterRoutes(api)
		s.billHandler.RegisterRoutes(api)
		s.scanHandler.RegisterRoutes(api)
		s.logoutHandler.RegisterRoutes(api)
		s.userPINHandler.RegisterRoutes(api)
	}

}

func (s *Server) registerHealthRoutes(api *gin.RouterGroup) {
	health := api.Group("/health")
	{
		health.GET("", s.healthCheck)
		health.GET("/ready", s.readinessCheck)
	}
}

// HealthCheck godoc
// @Summary Show the status of server.
// @Description get the status of server.
// @Tags health
// @Accept */*
// @Produce json
// @Success 200 {object} map[string]interface{}
// @Router /health [get]
func (s *Server) healthCheck(c *gin.Context) {
	c.JSON(200, gin.H{
		"status":  "healthy",
		"service": "github.com/novriyantoAli/moodly-api",
		"version": "1.0.0",
	})
}

// ReadinessCheck godoc
// @Summary Show the readiness of server.
// @Description get the readiness of server.
// @Tags health
// @Accept */*
// @Produce json
// @Success 200 {object} map[string]interface{}
// @Router /health/ready [get]
func (s *Server) readinessCheck(c *gin.Context) {
	c.JSON(200, gin.H{
		"status": "ready",
		"checks": gin.H{
			"database": "ok",
			"cache":    "ok",
		},
	})
}
